server:
  port: 8082
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.174.190
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.174.190
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
